#!/usr/bin/python -O
#-*- coding: utf-8 -*-
"""
cropper [file]

An app to easily crop an image into multiple pieces.
"""
from __future__ import with_statement, division, absolute_import
import gtk, gobject
gtk.gdk.threads_init()
#gobject.threads_init()
import pango
import gio
from gbuilder import BuilderWindow, resource
from box import Box
from boxmodel import BoxListStore
from imagespace import ImageSpace
from optparse import OptionParser
#from gobject.option import OptionParser # the args returned is just wrong
import sys, os, subprocess
import PIL.Image
from cStringIO import StringIO

BUFSIZE = 8*1024 #8K # Amount to read in one go

parser = OptionParser()
#parser.add_option("-f", "--file", dest="filename",
#                  help="write report to FILE", metavar="FILE")
#parser.add_option("-q", "--quiet",
#                  action="store_false", dest="verbose", default=True,
#                  help="don't print status messages to stdout")

def permIter(seq):
	"""
	Given some sequence 'seq', returns an iterator that gives
	all permutations of that sequence.
	"""
	# http://aspn.activestate.com/ASPN/Cookbook/Python/Recipe/105962
	## Base case
	if len(seq) == 1:
		yield seq[0]
	else:
		## Inductive case
		for i in range(len(seq)):
			element_slice = seq[i:i+1]
			rest_iter = permIter(seq[:i] + seq[i+1:])
			for rest in rest_iter:
				yield element_slice + rest

def make_absolute(fn):
	print "make_absolute:", fn,
	rv = gio.File(fn)
	print rv
	return rv.get_uri()

class Cropper(BuilderWindow):
	window = property(lambda self: self.wCropper)
	filename = None
	def __init__(self, options, args, *pargs, **kwargs):
		if __debug__: print 'Cropper.__init__()'
		#TODO: Put all of this into GtkBuilder
		self.model = BoxListStore()
		self.model.exist_image = 'filesave'
		self.model.no_exist_image = 'filenew'
		
		self.tvAreas.set_model(self.model)
		self.tvAreas.get_selection().set_mode(gtk.SELECTION_MULTIPLE)
		self.tvAreas.get_selection().connect('changed', self.on_selection_changed)
		
		self.isImage = ImageSpace(model=self.model, box=1)
		self.isImage.selection = self.tvAreas.get_selection()
		self.isImage.mode = ImageSpace.INSERT
		self.isImage.next_color = gtk.gdk.color_parse('#A0F')
		self.isImage.connect('box-added', self.on_box_added)
#		self.isImage.connect('insert-box-changed', self.on_insert_box_changed)
		self.swImage.add(self.isImage)
		
		self.crpExists = gtk.CellRendererPixbuf()
		self.crtFilename = gtk.CellRendererText()
		self.crtColor = gtk.CellRendererText()
		self.crtColor.set_property('background-set', True)
		self.crtColor.set_property('text', ' ')
		
		self.tvcFile = gtk.TreeViewColumn()
		self.tvcFile.set_sizing(gtk.TREE_VIEW_COLUMN_AUTOSIZE)
		self.tvcFile.pack_start(self.crpExists, False)
		self.tvcFile.set_attributes(self.crpExists, icon_name=10)
		self.tvcFile.pack_start(self.crtFilename, True)
		self.tvcFile.set_attributes(self.crtFilename, text=2)
		self.tvcColor = gtk.TreeViewColumn()
		self.tvcColor.set_sizing(gtk.TREE_VIEW_COLUMN_AUTOSIZE)
		self.tvcColor.pack_start(self.crtColor, True)
		self.tvcColor.set_attributes(self.crtColor, background_gdk=8)
		
		self.tvAreas.append_column(self.tvcFile)
		self.tvAreas.append_column(self.tvcColor)
		self.tvAreas.set_headers_visible(False)
		self.tvAreas.set_tooltip_column(11)
		
		if len(args):
			if __debug__: print "args: %r" % args
			self.Open(None, file=make_absolute(args[0]))
#		self.window.connect('key-press-event', self._keypress)
	
#	def _keypress(self, window, event):
#		if __debug__: print "Keypress: %r %r" % (event.keyval, event.state)
#		return False
	
	def present(self):
#		self.preshow()
		self.wCropper.show_all()
		self.wCropper.present()
	
	def add_box(self, fn, box, color=None):
		if color is not None:
			if isinstance(color, basestring):
				color = gtk.gdk.color_parse(color)
			if not isinstance(box, gtk.gdk.Rectangle):
				box = gtk.gdk.Rectangle(*box)
			box = Box(box, color)
		self.model.append([fn, box])
	
	def get_next_filename(self):
		# TODO: When we have the filename, turn it into a conglamoratation
		if self.filename is None:
			return ''
		before, after = os.path.splitext(self.filename)
		return '%s.%i%s' % (before, len(self.model), after)
	
	_color_iter = None
	def get_next_color(self, color):
		if self._color_iter is None:
			self._color_iter = (gtk.gdk.color_parse('#'+p) for p in permIter('F0A'))
		try:
			return self._color_iter.next()
		except StopIteration:
			self._color_iter = None
			return self.get_next_color(color)
	
	# Event handlers
	def on_delete_event(self, widget, event):
		gtk.main_quit()
	
	def on_box_added(self, widget, box):
		self.model.append([self.get_next_filename(), box])
		self.isImage.next_color = self.get_next_color(self.isImage.next_color)
	
	def on_selection_changed(self, selection):
		self.actions['Delete'].set_sensitive(bool(selection.count_selected_rows()))
	
	# Actions/UI stuff
	PROPS = 'expand', 'fill', 'padding', 'pack-type', 'position'
	def add_menubar(self, menubar):
		props = self.vbContent.child_get(self.mbMenu, *self.PROPS)
		self.vbContent.remove(self.mbMenu)
		self.mbMenu = menubar
		params = []
		for k,v in zip(self.PROPS, props):
			params += [k,v]
		self.vbContent.add_with_properties(self.mbMenu, *params)
	
	def add_toolbar(self, toolbar):
		props = self.vbContent.child_get(self.tbTools, *self.PROPS)
		self.vbContent.remove(self.tbTools)
		self.tbTools = toolbar
		params = []
		for k,v in zip(self.PROPS, props):
			params += [k,v]
		self.vbContent.add_with_properties(self.tbTools, *params)

#########
# ACTIONS
#########
	
	def Open(self, action, **kwargs):
		if __debug__: print 'Open'
		
		if 'file' in kwargs:
			filename = kwargs['file']
		else:
			dlg = gtk.FileChooserDialog(parent=self.wCropper,
				action=gtk.FILE_CHOOSER_ACTION_OPEN, 
				buttons=(
					gtk.STOCK_CANCEL, gtk.RESPONSE_CANCEL,
					gtk.STOCK_OPEN, gtk.RESPONSE_OK,
					)
				)
			dlg.set_use_preview_label(True)
			dlg.set_select_multiple(False)
			if dlg.run() in (gtk.RESPONSE_CANCEL, gtk.RESPONSE_NONE):
				dlg.destroy()
				return
			filename = dlg.get_uri()
			dlg.destroy()
		
		# Open image
		self.model.clear()
		self.filename = filename
		#self.isImage.image = gtk.gdk.pixbuf_new_from_file(filename)
		#Use gtk.gdk.PixbufLoader
		# open the file
		pbl = gtk.gdk.PixbufLoader()
		self.isImage.loadfrompixbuf(pbl)
		self._loadfromgio(pbl, gio.File(filename))
	
	imagedata = None
	
	def _loadfromgio(self, pbl, fil):
		#TODO: Reimplement progressive reading
		def _open(f, result):
			s = fil.read_finish(result)
			if s is None:
				#TODO: Check the error and inform the user
				pbl.close()
			else:
				data = s.read()
				self.imagedata += data
				pbl.write(data)
				pbl.close()
		self.imagedata = ''
		fil.read_async(_open)
	
	def Crop(self, action):
		if __debug__: print 'Crop'
		#TODO: Make this async
		#TODO: Ask if there's conflicts
		
		origin = PIL.Image.open(StringIO(self.imagedata))
		
		for fn, box in ((r[0],r[1]) for r in self.model):
			print "fn:", fn
			r = box.rect
			img = origin.crop((r.x, r.y, r.x+r.width, r.y+r.height))
			
			dest = gio.File(fn)
			ext = os.path.splitext(dest.get_basename())[1].lower()
			img.save(dest.replace('', False), PIL.Image.EXTENSION.get(ext, origin.format))
		# Update the model
		self.model.foreach(BoxListStore.row_changed)

	def Quit(self, action):
		self.wCropper.destroy()
	
	def Clear(self, action):
		if __debug__: print 'Clear'
		self.model.clear()
	
	def Cut(self, action):
		if __debug__: print 'Cut'
		pass
	
	def Copy(self, action):
		if __debug__: print 'Copy'
		pass
	
	def Paste(self, action):
		if __debug__: print 'Paste'
		pass
	
	def Delete(self, action):
		if __debug__: print 'Delete'
		model, rows = self.tvAreas.get_selection().get_selected_rows()
		rows = map(model.get_iter, rows)
		for row in rows:
			model.remove(row)
	
	def SelectAll(self, action):
		self.tvAreas.get_selection().select_all()
	
	def ZoomIn(self, action):
		self.isImage.zoom *= 1.1
	
	def ZoomOut(self, action):
		self.isImage.zoom /= 1.1
	
	def ZoomNormal(self, action):
		self.isImage.zoom = 1.0
	
	def ZoomFit(self, action):
		if __debug__: print "ZoomFit"
		self.isImage.zoom_to_size()
	
	def FlipHorizontal(self, action):
		pass
	
	def FlipVertical(self, action):
		pass
	
	def RotateCW(self, action):
		pass
	
	def RotateCCW(self, action):
		pass
	
	def EditPreferences(self, action):
		pass
	
	def AutoShrink(self, action):
		# Shrink boxes to image size
		pass
	
	def About(self, action):
		dlg = gtk.AboutDialog()
		props = {
#			'version': """$Revision: 104 $""",
			'name': 'cropper',
			'logo-icon-name': 'image',
			'authors': ['James Bliss <james.bliss@astro73.com>'],
			'copyright': u'\N{COPYRIGHT SIGN} 2008 James Bliss',
			'website': 'http://www.astro73.com/'
			}
		for k,v in props.iteritems():
			dlg.set_property(k,v)
		dlg.run()
		dlg.destroy()
	
	def Add(self, action, value):
		if action == value:
			if __debug__: print "Add"
			self.isImage.mode = ImageSpace.INSERT
	
	def Select(self, action, value):
		if action == value:
			if __debug__: print "Select"
			self.isImage.mode = ImageSpace.SELECT

if __name__ == '__main__':
	options, args = parser.parse_args(sys.argv[1:])
	app = Cropper(fname=resource('cropper.xml'), options=options, args=args)
	
#	app.add_box('test1.gif', ( 75,131,354,547), '#F0A')
#	app.add_box('test2.gif', ( 15, 22,467,191), '#AF0')
#	app.add_box('test3.gif', (273, 37,204,712), '#0AF')
#	app.add_box('test4.gif', ( 18,622,470,124), '#0F0')
#	app.add_box('test5.gif', ( 11, 20,178,722), '#00F')
#	app.isImage.image = gtk.gdk.pixbuf_new_from_file('test.gif')
#	app.isImage.mode = ImageSpace.INSERT
	
#	app.wCropper.set_default_size(700, 1000)
	
	# Run
	app.present()
	if __debug__: print "Model data:", map(tuple, app.model)
	gtk.gdk.set_show_events(True)
	gtk.main()
